### ISSUE TITLE
Image for the discord bot

### ISSUE THREAD

**Issue by pncnmnp** [MLH-Fellowship/Auto-Tagger#11]
A circular version of our logo with high resolution would be favorable.

**Comment by pncnmnp** [comment]
@CallmeMehdi can you update our current image?

**Comment by CallmeMehdi** [comment]
@pncnmnp I'm on it, it should be ready by 20h30 ( Tunisia time ), but what do you mean by our current image?

**Comment by pncnmnp** [comment]
The image present in our README. Are you planning on using some other logo for discord?

**Comment by pncnmnp** [comment]
@CallmeMehdi For the discord bot, I have cropped the current README logo. If you wish to present a new logo, kindly reopen this issue.
