### ISSUE TITLE
Running the discord bot documentation

### ISSUE THREAD

**Issue by CallmeMehdi** [MLH-Fellowship/Auto-Tagger#19]
So, when running the discord bot via "python discord_bot.py" you need to make sure of a couple of things:

- You have dotenv installed

- You have discord.py library installed

- Changing the LOAD_PATH to your own path of the BentoML served model

**Comment by pncnmnp** [comment]
@CallmeMehdi I have changed the Wiki section for [Running the bot on Discord](https://github.com/MLH-Fellowship/Auto-Tagger/wiki/Running-the-bot-on-Discord), to reflect the two additions - changing `LOAD_PATH` and installation instructions for `discord.py`.
Do review and close this issue.
(The .env instructions were already mentioned there)
