### ISSUE TITLE
Serving the model on BentoML

### ISSUE THREAD

**Issue by CallmeMehdi** [MLH-Fellowship/Auto-Tagger#2]
### In order to serve the NER model on BentoML you need to:

1. Download the model from this drive: https://drive.google.com/file/d/1TyuIoMO42CHHvQVlOpw6Ynco39rQbc6t/view?usp=sharing

2. Put it in the server/results/model.bin ( rename the file as model.bin )

3. Download the BERT uncased model from here: https://www.kaggle.com/abhishek/bert-base-uncased

4. Unzip the files in server/model

5. Run `python serving.py` inside server/src

6. Execute the command `bentoml serve PyTorchModel:latest`

The model will be served on **http://127.0.0.1:5000/**
 

### To send a request you'd need to send in a POST request with a json file like the example below:
`{
	"sentence": "Jack and James went to the university and they met Emily"
}`

### to **http://127.0.0.1:5000/predict**

The response will be a string of all the names detected separated by a ','. In this example it will be:

`jack,james,emily`

**Comment by pncnmnp** [comment]
For anyone who does not have a GPU and is facing the following issue: 
> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

In `serving.py`, change the `load_state_dict` part in `__main__` to `torch.load(config.MODEL_PATH, map_location='cpu')` 
Also, change all the `torch.device("gpu")` to `torch.device("cpu")`
