### ISSUE TITLE
Name-Surname pairs are not being predicted

### ISSUE THREAD

**Issue by pncnmnp** [MLH-Fellowship/Auto-Tagger#4]
As per our current model, only names are being predicted. For example: 
![Example-Name-Surname-Not-Predicting](https://user-images.githubusercontent.com/24948340/94360424-baa98e00-00ca-11eb-91eb-f2e2767ff7d9.png)

One quick fix would be to find out if the next word is a NNP (Proper Noun Singular Form) and predict the accuracy of it being a surname. Surname dataset for training: https://github.com/arineng/arincli/blob/master/lib/last-names.txt. We can even start with a simple search based approach.

**Comment by CallmeMehdi** [comment]
This can be a consequence of the dataset that the model was trained on. I looked into the dataset and it's mostly just first names ( No last names to be detected ).

This issue can be easily corrected by simply grabbing 1 word after the name that was detected, if the pair makes sense in the discord users list, then the bot tags that person, if not, it just uses the first name.

**Comment by CallmeMehdi** [comment]
@pncnmnp This issue is solved and we no longer need it. Make sure to close it and move it to done in GitHub Project, thank you.
